version: '3.7'

services:

  currency-exchange:
    image: ethanyixinsun/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - service-registry
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-conversion:
    image: ethanyixinsun/microservices-currency-conversion-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - service-registry
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: ethanyixinsun/microservices-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - service-registry
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  service-registry:
    image: ethanyixinsun/microservices-service-registry:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.12-management
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network:

