version: '3.7'

services:

  currency-exchange:
    image: ethanyixinsun/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  service-registry:
    image: ethanyixinsun/microservices-service-registry:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:

